Remove Custom Hook
AnnaViktorovna/react-todo pull request #9
Opened 2024-08-06 02:10 UTC by AnnaViktorovna

2024-08-16 15:39 UTC, gsvidal requested changes
You should make some fixes. Watch your Slack DM.

2024-08-16 15:39 UTC, gsvidal commented on src/App.jsx
>                  <AddTodoForm onAddTodo={addTodo} />
```suggestion
                <AddTodoForm onAddTodo={addTodo} inputRef={inputRef}/>
```

2024-08-16 15:39 UTC, gsvidal commented on src/AddTodoForm.jsx
>  export default function AddTodoForm({ onAddTodo }) {
```suggestion
export default function AddTodoForm({ onAddTodo, inputRef }) {
```

2024-08-16 15:39 UTC, gsvidal commented on src/assets/InputWithLabel.jsx
> +}, );
```suggestion
}, []);
```

2024-08-29 03:17 UTC, AnnaViktorovna reviewed
changes after revier's suggestions

2024-08-29 03:56 UTC, merged